---

services:
  app:
    build:
      context: .
    volumes:
      - ./:/build
      - ./build/devkit/extras/config/database.json:/build/config/database.json
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 3000:3000

  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 --password=root
      start_period: 20s
      start_interval: 1s
      interval: 30s
      timeout: 5s
      retries: 30

  phpmyadmin:
    image: phpmyadmin
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - 8080:80
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root

volumes:
  mariadb:
