---
start_on_boot: true
pause_on_net_down: true
resume_on_net_up: true
resume_on_wifi_conn: true
expirations:
  - minutes: 1
    mbytes: 1
    pause_limit: 3
    exp_days: 0

  - minutes: 1440 # 1 day
    mbytes: 1000 #1 GB
    pause_limit: 10
    exp_days: 1

  - minutes: 43200 # 30 days
    mbytes: 40000 # 40GB
    pause_limit: 99
    exp_days: 30
