---
- src: git
  git_url: https://github.com/AdoPiSoft/flarehotspot-theme.git

# - src: github
  # id: flarehotspot/wired-coinslot
  # branch: main

# - src: github
  # id: flarehotspot/wifi-hotspot
  # branch: main

# - src: github
  # id: flarehotspot/basic-system-account

# - src: github
  # id: flarehotspot/basic-net-mgr
