- uuid: wyOLUROd
  network: 10.0.0.0/20
  amount: 1
  time_mins: 30
  data_mbytes: 0
- uuid: weNUpAUF
  network: 10.0.0.0/20
  amount: 5
  time_mins: 60
  data_mbytes: 0
- uuid: ZPOXomqY
  network: 10.0.0.0/20
  amount: 10
  time_mins: 120
  data_mbytes: 0
