---
site_name: Flare Hotspot
site_url: https://developer.flarehotspot.com
site_description: 'Flare Hotspot platform for developers:
  Build. Innovate. Get Paid.'

theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: light-blue
  features:
    - navigation.sections
    - search.highlight
    - search.suggestions
    - content.code.annotate
    - content.code.copy
    - navigation.footer

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list

nav:
  - Guides:
      - 'Getting Started': guides/getting-started.md
      - 'Creating a plugin': guides/creating-a-plugin.md
      - 'Basic Routing': guides/basic-routing.md
      - 'Creating a link': guides/creating-a-link.md
      - 'Portal Items': guides/portal-items.md
      - 'Admin Navs': guides/admin-navs.md
      - 'Vue Components': guides/vue-components.md
      - 'Vue Response': guides/vue-response.md
      - 'Http Helpers': guides/http-helpers.md
      - 'Form Submission': guides/form-submission.md
      - 'Translations': guides/translations.md
      - 'Route Middlewares': guides/route-middlewares.md
      - 'Database Access': guides/database-access.md
      - 'Database Migrations': guides/database-migrations.md
  - Tutorials:
      - 'Manage Sessions': tutorials/manage-sessions.md
      - 'Accept Payments': tutorials/accepting-payments.md
      - 'Create Theme': tutorials/creating-a-theme
  - API Reference:
      - 'PluginApi': api/plugin-api.md
      - 'AccountsApi': api/accounts-api.md
      - 'HttpApi': api/http-api.md
  - Examples: examples/index.md

copyright: |
  &copy; 2024 <a href="https://www.flarego.ph">Flarego Technologies Corp.</a>

extra:
  generator: false
