---
site_name: Flare Hotspot Developers
site_url: https://developer.flarehotspot.com
site_description: 'Flare Hotspot platform for developers:
  Build. Innovate. Get Paid.'

theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: light-blue
  features:
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.suggestions
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list

nav:
  - Guides:
      - 'Getting Started': guides/getting-started.md
      - 'Creating a plugin': guides/creating-a-plugin.md
      - 'Routes and Links': guides/routes-and-links.md
      - 'Vue Components': guides/vue-components.md
      - 'Portal Items': guides/portal-items.md
      - 'Admin Navs': guides/admin-navs.md
      - 'Form Submission': guides/form-submission.md
      - 'Translations': guides/translations.md
      - 'Database Migrations': guides/database-migrations.md
  - Tutorials:
      - 'Manage Sessions': tutorials/manage-sessions.md
      - 'Accept Payments': tutorials/accepting-payments.md
      - 'Create Theme': tutorials/creating-a-theme
  - API Reference:
      - 'PluginApi': api/plugin-api.md
      - 'AccountsApi': api/accounts-api.md
      - 'HttpApi': api/http-api.md
      - 'HttpAuth': api/http-auth.md
      - 'HttpHelpers': api/http-helpers.md
      - 'HttpRouterApi': api/http-router-api.md
      - 'HttpResponse': api/http-response.md
      - 'VueRouterApi': api/vue-router-api.md
      - 'VueResponse': api/vue-response.md
      - '$flare': api/flare-variable.md
  - Free Plugins:
      - 'Flare Hotspot Theme': 'plugins/com.flarego.default-theme.md'

copyright: |
  &copy; 2024 <a href="https://www.flarego.ph">Flarego Technologies Corp.</a>

extra:
  generator: false
