---

site_name: Flare Hotspot
site_url: https://developer.flarehotspot.com
site_description: "Flare Hotspot platform for developers:
  Build. Innovate. Get Paid."

nav:
  - Getting Started: getting-started.md
  - API Reference: api-reference/index.md
